# Generated by Django 6.0.7 on 2026-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersecurity_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='password_hint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='recovery_key_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='security_answer_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='security_question',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='security_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersecurity',
            name='master_password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersecurity',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
