# Generated by Django 6.0.7 on 2026-07-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersecurity_password_hint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='recovery_key_hash',
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='security_answer_hash',
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='security_question',
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='security_setup_completed',
        ),
    ]
