# Generated by Django 6.0.7 on 2026-07-16 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securityquestion_remove_usersecurity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='recovery_key_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='security_answer_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.securityquestion'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='security_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
